# Experiment configuration for MIA
# All parameters correspond to argparse arguments in mia.py

dataset: breastmnist
model: "resnet9"
lr: 0.005
batchsize: 128
epochs: 25
n_targets: 512
pkeep: 0.5
debug: false
n_queries: 2
private: true
adapt_weights_to_budgets: true
accountant: rdp
individualize: sampling
weights: null
target_delta: 1e-12
max_grad_norm: 1.0
portions:
  - 0.2
  - 0.4
  - 0.6
  - 0.8
budgets:
  - 8.0
  - 32.0
n_parallel: 2
num_max_per_class_samples: 2000
disable_inner: true
seed: 42
train_and_save_models: true
compute_and_save_logits: true
compute_and_save_scores: true
compute_and_save_stats: true
plot_results: false
test_model: true