# Experiment configuration for MIA
# All parameters correspond to argparse arguments in mia.py

dataset: breast_cancer
batchsize: 32
target_delta: 1e-12
lr: 0.01
budgets:
  - 5.0
  - 20.0
model: null
epochs: 10
n_shadows: 5
n_targets: 512
pkeep: 0.5
debug: false
n_queries: 2
private: true
adapt_weights_to_budgets: true
accountant: rdp
individualize: sampling
weights: null
max_grad_norm: 1.0
portions:
  - 0.2
  - 0.4
  - 0.6
  - 0.8
n_parallel: 8
disable_inner: true
seed: 42
train_and_save_models: true
compute_and_save_logits: true
compute_and_save_scores: true
compute_and_save_stats: true
plot_results: false
test_model: true