# Experiment configuration for MIA
# All parameters correspond to argparse arguments in mia.py

dataset: credit_card_default
model: null
lr: 0.01
batchsize: 32
epochs: 50
n_targets: 128
pkeep: 0.5
debug: false
n_queries: 2
private: true
adapt_weights_to_budgets: true
accountant: rdp
individualize: sampling
weights: null
target_delta: 1e-12
max_grad_norm: 1.0
budgets:
  - 4.0
  - 8.0
  - 16.0
  - 32.0
budgets_attackee: 32.0
n_parallel: 32
disable_inner: true
seed: 42
train_and_save_models: false
compute_and_save_logits: false
test_model: false
compute_and_save_scores: false
compute_and_save_stats: true
plot_results: false